"""Apply checksum-bound pilot reviews and generate aggregate-only results, with no HTTP."""
from collections import Counter
import json
import os
from pathlib import Path
import time
from datetime import datetime
import fcntl

import lyrics_lrclib as l


def apply_reviews(c, reviews, root=l.ROOT):
    c.execute('CREATE TABLE IF NOT EXISTS review_history (song_id TEXT PRIMARY KEY, original_payload TEXT NOT NULL)')
    for review in reviews:
        row=c.execute('SELECT payload FROM results WHERE song_id=?',(review['song_id'],)).fetchone()
        if row is None: raise ValueError('Review references missing result')
        r=json.loads(row[0])
        if (r['matched'] or {}).get('id')!=review['lrclib_id']: raise ValueError('Review identity changed')
        canonical=root/'data/lyrics'/(r['song_id']+'.txt')
        quarantined=root/'data/cache/lrclib/quarantine'/(r['song_id']+'.txt')
        path=canonical if canonical.exists() else quarantined
        if path.is_symlink() or l.digest(path.read_bytes())!=review['lyrics_sha256']:
            raise ValueError('Review text checksum changed')
        r['review_status']='assistant_reviewed';r['review']=review
        if review.get('reject'):
            r['status']='ambiguous';r['reason']='Text review: '+review['finding']
            r['lyrics_path']=None;r['lyrics_sha256']=None
            r['quarantined_path']=str(quarantined.relative_to(root))
        with c:
            c.execute('INSERT OR IGNORE INTO review_history VALUES (?,?)',(r['song_id'],row[0]))
            c.execute('UPDATE results SET payload=? WHERE song_id=?',(json.dumps(r,ensure_ascii=False,sort_keys=True),r['song_id']))
        # Persist rejection before moving; rerunning completes an interrupted move.
        if review.get('reject') and canonical.exists():
            quarantined.parent.mkdir(parents=True,exist_ok=True)
            if quarantined.exists() and l.digest(quarantined.read_bytes())!=review['lyrics_sha256']:
                raise ValueError('Conflicting quarantine file')
            os.replace(canonical,quarantined)


def report(c, root=l.ROOT):
    rows=[json.loads(x[0]) for x in c.execute('SELECT payload FROM results ORDER BY song_id')]
    settings=dict(c.execute('SELECT * FROM settings'))
    reviews=[r['review'] for r in rows if 'review' in r]
    counts=Counter(r['status'] for r in rows)
    attempts=[json.loads(p.read_text()) for p in (root/'data/cache/lrclib').glob('*-attempt-*.json')]
    calls=len(attempts)
    # Estimate acquisition only, excluding later editorial review time.
    first=datetime.fromisoformat(settings['started_at'])
    last=datetime.fromisoformat(settings.get('finished_at',settings['started_at']))
    seconds=(last-first).total_seconds()
    estimate_requests=round(calls/len(rows)*25363) if rows else 0
    estimate_hours=seconds/len(rows)*25363/3600 if rows else 0
    supported=[r for r in rows if r['metadata']['durations']]
    selected_support=[r for r in rows if r['status']=='success' and any(e['id']==r['selected'] and e['duration_support'] for e in r['candidates'])]
    selected_album=[r for r in rows if r['status']=='success' and any(e['id']==r['selected'] and e['album_support'] for e in r['candidates'])]
    metadata_comparison=[]
    for r in rows:
        if not r['metadata']['durations'] and not r['metadata']['albums']: continue
        cache=root/'data/cache/lrclib'/(l.digest(r['retrievals'][-1]['url'].encode())+'.json')
        candidates=l.parse(json.loads(cache.read_text()))
        with_metadata=l.decide(r,candidates)
        without_metadata=l.decide(dict(r,metadata={'durations':[],'albums':[]}),candidates)
        metadata_comparison.append({'title':r['title'],'with':with_metadata['status'],'without':without_metadata['status'],
                                    'selected_changed':with_metadata['selected']!=without_metadata['selected']})
    data={'attempted':len(rows),'counts':dict(counts),'requests':calls,'http_statuses':dict(Counter(str(a['status']) for a in attempts)),
          'elapsed_seconds':round(seconds,2),'estimated_full_requests':estimate_requests,'estimated_full_hours':round(estimate_hours,2),
          'metadata_comparison':metadata_comparison,'reviewed':len(reviews),'review_rejections':sum(bool(r.get('reject')) for r in reviews),
          'assets_with_duration':len(supported),'successes_with_duration_support':len(selected_support),
          'successes_with_album_support':len(selected_album),'periods':[]}
    for lo,hi,label in l.PERIODS:
        group=[r for r in rows if lo<=int(r['first_chart_date'][:4])<=hi]
        co=Counter(r['status'] for r in group)
        data['periods'].append(dict(period=label,attempted=len(group),counts=dict(co),coverage=round(100*co['success']/len(group),2) if group else 0))
    lines=['# LRCLIB technical pilot results','',
           'Generated by `python3 src/lyrics_pilot_report.py` from the frozen pilot sidecar and checksum-bound reviews. No lyrics are included.', '',
           'The user authorized this local-only 200-song technical pilot after the earlier source assessment. Full acquisition remains explicitly unstarted.', '',
           f"Attempted **{len(rows)}/200**; high-confidence usable texts **{counts['success']}**; ambiguous **{counts['ambiguous']}**; not found **{counts['not_found']}**; errors **{counts['error']}**. Usable coverage: **{100*counts['success']/len(rows):.1f}%**.", '',
           '| First-chart period | Attempted | Usable | Ambiguous | Not found | Errors | Usable coverage |',
           '|---|---:|---:|---:|---:|---:|---:|']
    for p in data['periods']:
        co=Counter(p['counts'])
        lines.append(f"| {p['period']} | {p['attempted']} | {co['success']} | {co['ambiguous']} | {co['not_found']} | {co['error']} | {p['coverage']}% |")
    lines += ['', '2015–2019 overlaps 2010–2019. Periods use first Billboard appearance, not release dates. Instrumental candidates are unresolved/ambiguous rather than empty successful lyric files.', '',
              '## Quality review','',
              f"Codex B inspected {len(reviews)} initially successful assets using the scopes recorded in [the review ledger](lyrics_pilot_review.json). {data['review_rejections']} were removed from usable coverage and quarantined. These are assistant text/metadata reviews, not human or audio-verified ground truth.", '',
              'No obvious wrong-artist, same-title substitution, or cover substitution was observed in the inspected successful set. This does not establish transcription accuracy, completeness, or absence of subtle version substitution. Masked words occurred without clean-version flags in the source metadata.', '',
              'Rejected texts and all raw responses remain private. Review findings are bound to the selected LRCLIB ID and exact text SHA-256. Original decisions remain in `review_history`; rerunning the report applies reviews idempotently.', '',
              f"Duration metadata was available for {len(supported)} pilot assets; {len(selected_support)} usable selections have a duration within two seconds of at least one linked recording. {len(selected_album)} usable selections match an available album/release title. Metadata is a frozen read-only snapshot, not refreshed as Codex A progresses. Multiple linked recordings and reissues make it supporting evidence rather than authoritative version selection.", '',
              'Offline comparison without metadata left most outcomes unchanged: metadata changed two accepted source IDs and blocked the 165-second candidate for Steady Mobbin\' (available metadata: 310 and 393 seconds). It did not increase accepted asset count or resolve competing texts. The comparisons are preserved in the local summary JSON.', '',
              '### Observed review findings','']
    for r in reviews:
        if r.get('reject') or not r['finding'].startswith('No obvious'):
            lines.append(f"- {r['title']} — {r['artist']}: {r['finding']}")
    lines += ['', '### Unresolved reasons','']
    for reason,n in sorted(Counter(r['reason'] for r in rows if r['status']!='success').items()):
        lines.append(f'- {n}: {reason}')
    lines += ['', '## Engineering','',
              '- Corpus: `data/lyrics/<song_id>.txt`. Private state: `data/processed/lyrics.db`. Private responses and quarantine: `data/cache/lrclib/`.',
              '- Resume: `python3 src/lyrics_lrclib.py run`. This command is restricted to the same 200 assets, preserves successful files, and skips persisted results. Terminal failures are cached; resume does not automatically retry them.',
              '- Validate: `python3 src/lyrics_lrclib.py validate`. Regenerate this report/apply reviews: `python3 src/lyrics_pilot_report.py`.',
              '- Later deterministic import, only after the metadata writer stops: `python3 src/lyrics_lrclib.py import --metadata-stopped`. Import was not run. The unified lyrics manifest remains stale until import; its canonical-file validation will see sidecar-owned files as unmanifested in the meantime.',
              '- Sequential identified API requests use a persistent 500 ms minimum inter-request delay, respect Retry-After, retry transient failures up to three attempts, and preserve every HTTP attempt. Cached payloads carry retrieval time and SHA-256.',
              f'- Observed HTTP attempts: {calls}; statuses: {data["http_statuses"]}. Acquisition elapsed: {seconds/60:.2f} minutes.',
              f'- Linear full-population estimate under these conditions: about {estimate_requests:,} HTTP attempts and {estimate_hours:.2f} hours, excluding human review, long throttles, and changed catalogue conditions. This is an extrapolation, not authorization or a full-corpus execution plan.', '',
              '## Recommendation','',
              '**NO-GO for unattended full acquisition with the current acceptance rules.** Local acquisition works, but reviewed text defects demonstrate that identity agreement does not guarantee a complete, clean research input. Resolve text-quality checks and review the weak period/credit coverage before scaling. No classifier or full-population acquisition was started.', '']
    l.atomic(root/'reports/lyrics_pilot_results.md','\n'.join(lines).encode())
    l.save_json(root/'data/processed/lyrics_pilot_summary.json',data)
    return data


if __name__=='__main__':
    l.guards()
    with (l.ROOT/'data/processed/lyrics.lock').open('w') as lock:
        fcntl.flock(lock,fcntl.LOCK_EX|fcntl.LOCK_NB)
        c=l.database()
        reviews=json.loads((l.ROOT/'reports/lyrics_pilot_review.json').read_text())['reviews']
        apply_reviews(c,reviews)
        l.validate(c)
        print(json.dumps(report(c),ensure_ascii=False,indent=2));c.close()
